apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.mongoExpressName }}-depl
  labels:
    app: {{ .Values.app.mongoExpressName }}
spec:
  replicas: {{ .Values.app.replicas }}
  revisionHistoryLimit: {{ .Values.app.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: {{ .Values.app.mongoExpressName }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.mongoExpressName }}
      annotations:
        chechsum/config: {{ include (print $.Template.BasePath "/mongo-configmap.yml") . | sha256sum }}
    spec:
      containers:
      - name: {{ .Values.app.mongoExpressName }}
        image: {{ .Values.mongoExpress.image.image }}
        resources:
          limits:
            memory: "{{ .Values.app.limits.memory }}"
            cpu: "{{ .Values.app.limits.cpu }}"
        ports:
        - containerPort: {{ .Values.mongoExpress.image.port }}
        env:
          {{- if .Values.mongoExpress.service.type.enabled }}
          - name: TST
            value: "true"
          {{- end }}
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            valueFrom:
              secretKeyRef:
                name: {{ .Values.app.mongodbName }}-secret
                key: mongo-root-username
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.app.mongodbName }}-secret
                key: mongo-root-password
          - name: ME_CONFIG_MONGODB_SERVER
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.app.mongodbName }}-configmap
                key: db-url
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.mongoExpressName }}-service
spec:
  selector:
    app: {{ .Values.app.mongoExpressName }} # key and value must be the same as in Deployment.spec.[selector.matchLabels | template.metadata.labels]
  {{- if .Values.mongoExpress.service.type.enabled }}
  type: {{ .Values.mongoExpress.service.type.value }}
  {{- end }}
  ports:
  - port: {{ .Values.mongoExpress.service.exposePort }}
    targetPort: {{ .Values.mongoExpress.image.port }}
    {{- if .Values.mongoExpress.service.type.enabled }}
    nodePort: {{ .Values.mongoExpress.service.type.nodePort }}
    {{- end }}
