apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.mongodbName }}-secret
type: Opaque
data:
  mongo-root-username: {{ .Values.mondoSecret.mongoRootUsername }}
  mongo-root-password: {{ .Values.mondoSecret.mongoRootPassword }}
